language: cpp

dist: bionic
stages:
  - build

matrix:
  include:
    #
    - name: 
      os: linux
      stage: build
      compiler: clang
      addons:
        apt:
          packages:
            - clang-format-8
    - name: Linux editor (debug, GCC 9)
      os: linux 
    #
    - os: linux
      stage: build
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env:
        - CC=gcc-7

# Install dependencies
addons:
  apt:
    packages:
      - cmake

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    fi

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install -y libglew-dev libgtest-dev libsdl2-dev libsubunit-dev
  - sudo apt-get install -y libsdl2-dev libglew-dev libvulkan-dev libgl1-mesa-dev opencl-headers libzip-dev libfswatch-dev libfreeimage-dev libfswatch-dev libxml2-dev

# Build executable.
script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest -VV

#  cmake -DCMAKE_TOOLCHAIN_FILE=android.toolchain.cmake -DANDROID_NDK=<ndk_path> -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="armeabi-v7a with NEON" <source_path> &&